sudo: required
services:
  - docker

before_install:
  - docker build -t himanshu0202/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run himanshu0202/react-test npm test -- --coverage
  
after_success:
  - docker build -t himanshu0202/multi-client ./client  
  - docker build -t himanshu0202/multi-nginx ./nginx
  - docker build -t himanshu0202/multi-server ./server
  - docker build -t himanshu0202/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub 
  - docker push himanshu0202/multi-client
  - docker push himanshu0202/multi-nginx
  - docker push himanshu0202/multi-server
  - docker push himanshu0202/multi-worker